---
- include_vars: 
    file: "../vars/main.yml"

- include_tasks: install_local_package.yml
  vars:
    package: "{{ item.package }}"
    version: "{{ item.versions }}"
  with_items:
   - "{{ packages }}"