---
- name: Download Terraform
  ansible.builtin.get_url:
    url: https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
    dest: /tmp/terraform.zip
    mode: '0755'
  become: true
  become_user: root

- name: Unarchive Terraform
  ansible.builtin.unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin
    remote_src: yes
  become: true
  become_user: root

- name: Ensure Terraform binary has correct permissions
  ansible.builtin.file:
    path: /usr/local/bin/terraform
    mode: '0755'
  become: true
  become_user: root
